# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(554, 456)
        self.input_log = QtWidgets.QLineEdit(Dialog)
        self.input_log.setGeometry(QtCore.QRect(70, 40, 381, 20))
        self.input_log.setObjectName("input_log")
        self.input_pass = QtWidgets.QLineEdit(Dialog)
        self.input_pass.setGeometry(QtCore.QRect(70, 80, 381, 20))
        self.input_pass.setObjectName("input_pass")
        self.input_keyword = QtWidgets.QLineEdit(Dialog)
        self.input_keyword.setGeometry(QtCore.QRect(70, 250, 471, 20))
        self.input_keyword.setObjectName("input_keyword")
        self.input_reslink = QtWidgets.QLineEdit(Dialog)
        self.input_reslink.setGeometry(QtCore.QRect(70, 290, 471, 20))
        self.input_reslink.setObjectName("input_reslink")
        self.bg_img = QtWidgets.QLabel(Dialog)
        self.bg_img.setGeometry(QtCore.QRect(-10, 0, 751, 471))
        self.bg_img.setStyleSheet("background-image: url(maxresdefault.jpg);")
        self.bg_img.setText("")
        self.bg_img.setPixmap(QtGui.QPixmap("maxresdefault.jpg"))
        self.bg_img.setScaledContents(True)
        self.bg_img.setObjectName("bg_img")
        self.text_log = QtWidgets.QLabel(Dialog)
        self.text_log.setGeometry(QtCore.QRect(410, 40, 91, 16))
        self.text_log.setObjectName("text_log")
        self.text_pass = QtWidgets.QLabel(Dialog)
        self.text_pass.setGeometry(QtCore.QRect(410, 80, 47, 13))
        self.text_pass.setObjectName("text_pass")
        self.text_keyword = QtWidgets.QLabel(Dialog)
        self.text_keyword.setGeometry(QtCore.QRect(490, 250, 47, 13))
        self.text_keyword.setObjectName("text_keyword")
        self.text_reslink = QtWidgets.QLabel(Dialog)
        self.text_reslink.setGeometry(QtCore.QRect(480, 290, 71, 20))
        self.text_reslink.setObjectName("text_reslink")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(240, 430, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.bg_img.raise_()
        self.input_log.raise_()
        self.input_pass.raise_()
        self.input_keyword.raise_()
        self.input_reslink.raise_()
        self.text_log.raise_()
        self.text_pass.raise_()
        self.text_keyword.raise_()
        self.text_reslink.raise_()
        self.pushButton.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.text_log.setText(_translate("Dialog", "LOGIN"))
        self.text_pass.setText(_translate("Dialog", "PASS"))
        self.text_keyword.setText(_translate("Dialog", "Keyword"))
        self.text_reslink.setText(_translate("Dialog", "ResumeLink"))
        self.pushButton.setText(_translate("Dialog", "Ок"))
# import image_rc
